# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deepthought.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deepthought.proto',
  package='deepthought',
  syntax='proto3',
  serialized_options=b'\n,io.github.ymmt2005.grpc_tutorial.deepthoughtZ0github.com/ymmt2005/grpc-tutorial/go/deepthought',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64\x65\x65pthought.proto\x12\x0b\x64\x65\x65pthought\"\r\n\x0b\x42ootRequest\"\x1f\n\x0c\x42ootResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0cInferRequest\x12\r\n\x05query\x18\x01 \x01(\t\"4\n\rInferResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\x12\x12\x13\n\x0b\x64\x65scription\x18\x02 \x03(\t2\x88\x01\n\x07\x43ompute\x12=\n\x04\x42oot\x12\x18.deepthought.BootRequest\x1a\x19.deepthought.BootResponse0\x01\x12>\n\x05Infer\x12\x19.deepthought.InferRequest\x1a\x1a.deepthought.InferResponseB`\n,io.github.ymmt2005.grpc_tutorial.deepthoughtZ0github.com/ymmt2005/grpc-tutorial/go/deepthoughtb\x06proto3'
)




_BOOTREQUEST = _descriptor.Descriptor(
  name='BootRequest',
  full_name='deepthought.BootRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=47,
)


_BOOTRESPONSE = _descriptor.Descriptor(
  name='BootResponse',
  full_name='deepthought.BootResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='deepthought.BootResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=80,
)


_INFERREQUEST = _descriptor.Descriptor(
  name='InferRequest',
  full_name='deepthought.InferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='deepthought.InferRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=111,
)


_INFERRESPONSE = _descriptor.Descriptor(
  name='InferResponse',
  full_name='deepthought.InferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='deepthought.InferResponse.answer', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='deepthought.InferResponse.description', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['BootRequest'] = _BOOTREQUEST
DESCRIPTOR.message_types_by_name['BootResponse'] = _BOOTRESPONSE
DESCRIPTOR.message_types_by_name['InferRequest'] = _INFERREQUEST
DESCRIPTOR.message_types_by_name['InferResponse'] = _INFERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BootRequest = _reflection.GeneratedProtocolMessageType('BootRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOOTREQUEST,
  '__module__' : 'deepthought_pb2'
  # @@protoc_insertion_point(class_scope:deepthought.BootRequest)
  })
_sym_db.RegisterMessage(BootRequest)

BootResponse = _reflection.GeneratedProtocolMessageType('BootResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOTRESPONSE,
  '__module__' : 'deepthought_pb2'
  # @@protoc_insertion_point(class_scope:deepthought.BootResponse)
  })
_sym_db.RegisterMessage(BootResponse)

InferRequest = _reflection.GeneratedProtocolMessageType('InferRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFERREQUEST,
  '__module__' : 'deepthought_pb2'
  # @@protoc_insertion_point(class_scope:deepthought.InferRequest)
  })
_sym_db.RegisterMessage(InferRequest)

InferResponse = _reflection.GeneratedProtocolMessageType('InferResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFERRESPONSE,
  '__module__' : 'deepthought_pb2'
  # @@protoc_insertion_point(class_scope:deepthought.InferResponse)
  })
_sym_db.RegisterMessage(InferResponse)


DESCRIPTOR._options = None

_COMPUTE = _descriptor.ServiceDescriptor(
  name='Compute',
  full_name='deepthought.Compute',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=168,
  serialized_end=304,
  methods=[
  _descriptor.MethodDescriptor(
    name='Boot',
    full_name='deepthought.Compute.Boot',
    index=0,
    containing_service=None,
    input_type=_BOOTREQUEST,
    output_type=_BOOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Infer',
    full_name='deepthought.Compute.Infer',
    index=1,
    containing_service=None,
    input_type=_INFERREQUEST,
    output_type=_INFERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPUTE)

DESCRIPTOR.services_by_name['Compute'] = _COMPUTE

# @@protoc_insertion_point(module_scope)
